/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the InterfaceCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfaceCreate{}

// InterfaceCreate struct for InterfaceCreate
type InterfaceCreate struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	// For BRIDGE `type` the following attribute is required: bridge_members. For LINK_AGGREGATION `type` the following attributes are required: lag_ports, lag_protocol. For VLAN `type` the following attributes are required: vlan_parent_interface, vlan_tag and vlan_pcp.
	Type                   *string                  `json:"type,omitempty"`
	Ipv4Dhcp               *bool                    `json:"ipv4_dhcp,omitempty"`
	Ipv6Auto               *bool                    `json:"ipv6_auto,omitempty"`
	Aliases                []InterfaceAlias         `json:"aliases,omitempty"`
	FailoverCritical       *bool                    `json:"failover_critical,omitempty"`
	FailoverGroup          NullableInt32            `json:"failover_group,omitempty"`
	FailoverVhid           NullableInt32            `json:"failover_vhid,omitempty"`
	FailoverAliases        []InterfaceFailoverAlias `json:"failover_aliases,omitempty"`
	FailoverVirtualAliases []InterfaceVirtualAlias  `json:"failover_virtual_aliases,omitempty"`
	BridgeMembers          []interface{}            `json:"bridge_members,omitempty"`
	Stp                    *bool                    `json:"stp,omitempty"`
	LagProtocol            *string                  `json:"lag_protocol,omitempty"`
	XmitHashPolicy         NullableString           `json:"xmit_hash_policy,omitempty"`
	LacpduRate             NullableString           `json:"lacpdu_rate,omitempty"`
	LagPorts               []string                 `json:"lag_ports,omitempty"`
	VlanParentInterface    *string                  `json:"vlan_parent_interface,omitempty"`
	VlanTag                *int32                   `json:"vlan_tag,omitempty"`
	VlanPcp                NullableInt32            `json:"vlan_pcp,omitempty"`
	Mtu                    NullableInt32            `json:"mtu,omitempty"`
}

// NewInterfaceCreate instantiates a new InterfaceCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfaceCreate() *InterfaceCreate {
	this := InterfaceCreate{}
	var description string = ""
	this.Description = &description
	var ipv4Dhcp bool = false
	this.Ipv4Dhcp = &ipv4Dhcp
	var ipv6Auto bool = false
	this.Ipv6Auto = &ipv6Auto
	var failoverCritical bool = false
	this.FailoverCritical = &failoverCritical
	var stp bool = true
	this.Stp = &stp
	return &this
}

// NewInterfaceCreateWithDefaults instantiates a new InterfaceCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfaceCreateWithDefaults() *InterfaceCreate {
	this := InterfaceCreate{}
	var description string = ""
	this.Description = &description
	var ipv4Dhcp bool = false
	this.Ipv4Dhcp = &ipv4Dhcp
	var ipv6Auto bool = false
	this.Ipv6Auto = &ipv6Auto
	var failoverCritical bool = false
	this.FailoverCritical = &failoverCritical
	var stp bool = true
	this.Stp = &stp
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InterfaceCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InterfaceCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InterfaceCreate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InterfaceCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InterfaceCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InterfaceCreate) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InterfaceCreate) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InterfaceCreate) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InterfaceCreate) SetType(v string) {
	o.Type = &v
}

// GetIpv4Dhcp returns the Ipv4Dhcp field value if set, zero value otherwise.
func (o *InterfaceCreate) GetIpv4Dhcp() bool {
	if o == nil || IsNil(o.Ipv4Dhcp) {
		var ret bool
		return ret
	}
	return *o.Ipv4Dhcp
}

// GetIpv4DhcpOk returns a tuple with the Ipv4Dhcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetIpv4DhcpOk() (*bool, bool) {
	if o == nil || IsNil(o.Ipv4Dhcp) {
		return nil, false
	}
	return o.Ipv4Dhcp, true
}

// HasIpv4Dhcp returns a boolean if a field has been set.
func (o *InterfaceCreate) HasIpv4Dhcp() bool {
	if o != nil && !IsNil(o.Ipv4Dhcp) {
		return true
	}

	return false
}

// SetIpv4Dhcp gets a reference to the given bool and assigns it to the Ipv4Dhcp field.
func (o *InterfaceCreate) SetIpv4Dhcp(v bool) {
	o.Ipv4Dhcp = &v
}

// GetIpv6Auto returns the Ipv6Auto field value if set, zero value otherwise.
func (o *InterfaceCreate) GetIpv6Auto() bool {
	if o == nil || IsNil(o.Ipv6Auto) {
		var ret bool
		return ret
	}
	return *o.Ipv6Auto
}

// GetIpv6AutoOk returns a tuple with the Ipv6Auto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetIpv6AutoOk() (*bool, bool) {
	if o == nil || IsNil(o.Ipv6Auto) {
		return nil, false
	}
	return o.Ipv6Auto, true
}

// HasIpv6Auto returns a boolean if a field has been set.
func (o *InterfaceCreate) HasIpv6Auto() bool {
	if o != nil && !IsNil(o.Ipv6Auto) {
		return true
	}

	return false
}

// SetIpv6Auto gets a reference to the given bool and assigns it to the Ipv6Auto field.
func (o *InterfaceCreate) SetIpv6Auto(v bool) {
	o.Ipv6Auto = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *InterfaceCreate) GetAliases() []InterfaceAlias {
	if o == nil || IsNil(o.Aliases) {
		var ret []InterfaceAlias
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetAliasesOk() ([]InterfaceAlias, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *InterfaceCreate) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []InterfaceAlias and assigns it to the Aliases field.
func (o *InterfaceCreate) SetAliases(v []InterfaceAlias) {
	o.Aliases = v
}

// GetFailoverCritical returns the FailoverCritical field value if set, zero value otherwise.
func (o *InterfaceCreate) GetFailoverCritical() bool {
	if o == nil || IsNil(o.FailoverCritical) {
		var ret bool
		return ret
	}
	return *o.FailoverCritical
}

// GetFailoverCriticalOk returns a tuple with the FailoverCritical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetFailoverCriticalOk() (*bool, bool) {
	if o == nil || IsNil(o.FailoverCritical) {
		return nil, false
	}
	return o.FailoverCritical, true
}

// HasFailoverCritical returns a boolean if a field has been set.
func (o *InterfaceCreate) HasFailoverCritical() bool {
	if o != nil && !IsNil(o.FailoverCritical) {
		return true
	}

	return false
}

// SetFailoverCritical gets a reference to the given bool and assigns it to the FailoverCritical field.
func (o *InterfaceCreate) SetFailoverCritical(v bool) {
	o.FailoverCritical = &v
}

// GetFailoverGroup returns the FailoverGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InterfaceCreate) GetFailoverGroup() int32 {
	if o == nil || IsNil(o.FailoverGroup.Get()) {
		var ret int32
		return ret
	}
	return *o.FailoverGroup.Get()
}

// GetFailoverGroupOk returns a tuple with the FailoverGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InterfaceCreate) GetFailoverGroupOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailoverGroup.Get(), o.FailoverGroup.IsSet()
}

// HasFailoverGroup returns a boolean if a field has been set.
func (o *InterfaceCreate) HasFailoverGroup() bool {
	if o != nil && o.FailoverGroup.IsSet() {
		return true
	}

	return false
}

// SetFailoverGroup gets a reference to the given NullableInt32 and assigns it to the FailoverGroup field.
func (o *InterfaceCreate) SetFailoverGroup(v int32) {
	o.FailoverGroup.Set(&v)
}

// SetFailoverGroupNil sets the value for FailoverGroup to be an explicit nil
func (o *InterfaceCreate) SetFailoverGroupNil() {
	o.FailoverGroup.Set(nil)
}

// UnsetFailoverGroup ensures that no value is present for FailoverGroup, not even an explicit nil
func (o *InterfaceCreate) UnsetFailoverGroup() {
	o.FailoverGroup.Unset()
}

// GetFailoverVhid returns the FailoverVhid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InterfaceCreate) GetFailoverVhid() int32 {
	if o == nil || IsNil(o.FailoverVhid.Get()) {
		var ret int32
		return ret
	}
	return *o.FailoverVhid.Get()
}

// GetFailoverVhidOk returns a tuple with the FailoverVhid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InterfaceCreate) GetFailoverVhidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailoverVhid.Get(), o.FailoverVhid.IsSet()
}

// HasFailoverVhid returns a boolean if a field has been set.
func (o *InterfaceCreate) HasFailoverVhid() bool {
	if o != nil && o.FailoverVhid.IsSet() {
		return true
	}

	return false
}

// SetFailoverVhid gets a reference to the given NullableInt32 and assigns it to the FailoverVhid field.
func (o *InterfaceCreate) SetFailoverVhid(v int32) {
	o.FailoverVhid.Set(&v)
}

// SetFailoverVhidNil sets the value for FailoverVhid to be an explicit nil
func (o *InterfaceCreate) SetFailoverVhidNil() {
	o.FailoverVhid.Set(nil)
}

// UnsetFailoverVhid ensures that no value is present for FailoverVhid, not even an explicit nil
func (o *InterfaceCreate) UnsetFailoverVhid() {
	o.FailoverVhid.Unset()
}

// GetFailoverAliases returns the FailoverAliases field value if set, zero value otherwise.
func (o *InterfaceCreate) GetFailoverAliases() []InterfaceFailoverAlias {
	if o == nil || IsNil(o.FailoverAliases) {
		var ret []InterfaceFailoverAlias
		return ret
	}
	return o.FailoverAliases
}

// GetFailoverAliasesOk returns a tuple with the FailoverAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetFailoverAliasesOk() ([]InterfaceFailoverAlias, bool) {
	if o == nil || IsNil(o.FailoverAliases) {
		return nil, false
	}
	return o.FailoverAliases, true
}

// HasFailoverAliases returns a boolean if a field has been set.
func (o *InterfaceCreate) HasFailoverAliases() bool {
	if o != nil && !IsNil(o.FailoverAliases) {
		return true
	}

	return false
}

// SetFailoverAliases gets a reference to the given []InterfaceFailoverAlias and assigns it to the FailoverAliases field.
func (o *InterfaceCreate) SetFailoverAliases(v []InterfaceFailoverAlias) {
	o.FailoverAliases = v
}

// GetFailoverVirtualAliases returns the FailoverVirtualAliases field value if set, zero value otherwise.
func (o *InterfaceCreate) GetFailoverVirtualAliases() []InterfaceVirtualAlias {
	if o == nil || IsNil(o.FailoverVirtualAliases) {
		var ret []InterfaceVirtualAlias
		return ret
	}
	return o.FailoverVirtualAliases
}

// GetFailoverVirtualAliasesOk returns a tuple with the FailoverVirtualAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetFailoverVirtualAliasesOk() ([]InterfaceVirtualAlias, bool) {
	if o == nil || IsNil(o.FailoverVirtualAliases) {
		return nil, false
	}
	return o.FailoverVirtualAliases, true
}

// HasFailoverVirtualAliases returns a boolean if a field has been set.
func (o *InterfaceCreate) HasFailoverVirtualAliases() bool {
	if o != nil && !IsNil(o.FailoverVirtualAliases) {
		return true
	}

	return false
}

// SetFailoverVirtualAliases gets a reference to the given []InterfaceVirtualAlias and assigns it to the FailoverVirtualAliases field.
func (o *InterfaceCreate) SetFailoverVirtualAliases(v []InterfaceVirtualAlias) {
	o.FailoverVirtualAliases = v
}

// GetBridgeMembers returns the BridgeMembers field value if set, zero value otherwise.
func (o *InterfaceCreate) GetBridgeMembers() []interface{} {
	if o == nil || IsNil(o.BridgeMembers) {
		var ret []interface{}
		return ret
	}
	return o.BridgeMembers
}

// GetBridgeMembersOk returns a tuple with the BridgeMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetBridgeMembersOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.BridgeMembers) {
		return nil, false
	}
	return o.BridgeMembers, true
}

// HasBridgeMembers returns a boolean if a field has been set.
func (o *InterfaceCreate) HasBridgeMembers() bool {
	if o != nil && !IsNil(o.BridgeMembers) {
		return true
	}

	return false
}

// SetBridgeMembers gets a reference to the given []interface{} and assigns it to the BridgeMembers field.
func (o *InterfaceCreate) SetBridgeMembers(v []interface{}) {
	o.BridgeMembers = v
}

// GetStp returns the Stp field value if set, zero value otherwise.
func (o *InterfaceCreate) GetStp() bool {
	if o == nil || IsNil(o.Stp) {
		var ret bool
		return ret
	}
	return *o.Stp
}

// GetStpOk returns a tuple with the Stp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetStpOk() (*bool, bool) {
	if o == nil || IsNil(o.Stp) {
		return nil, false
	}
	return o.Stp, true
}

// HasStp returns a boolean if a field has been set.
func (o *InterfaceCreate) HasStp() bool {
	if o != nil && !IsNil(o.Stp) {
		return true
	}

	return false
}

// SetStp gets a reference to the given bool and assigns it to the Stp field.
func (o *InterfaceCreate) SetStp(v bool) {
	o.Stp = &v
}

// GetLagProtocol returns the LagProtocol field value if set, zero value otherwise.
func (o *InterfaceCreate) GetLagProtocol() string {
	if o == nil || IsNil(o.LagProtocol) {
		var ret string
		return ret
	}
	return *o.LagProtocol
}

// GetLagProtocolOk returns a tuple with the LagProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetLagProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.LagProtocol) {
		return nil, false
	}
	return o.LagProtocol, true
}

// HasLagProtocol returns a boolean if a field has been set.
func (o *InterfaceCreate) HasLagProtocol() bool {
	if o != nil && !IsNil(o.LagProtocol) {
		return true
	}

	return false
}

// SetLagProtocol gets a reference to the given string and assigns it to the LagProtocol field.
func (o *InterfaceCreate) SetLagProtocol(v string) {
	o.LagProtocol = &v
}

// GetXmitHashPolicy returns the XmitHashPolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InterfaceCreate) GetXmitHashPolicy() string {
	if o == nil || IsNil(o.XmitHashPolicy.Get()) {
		var ret string
		return ret
	}
	return *o.XmitHashPolicy.Get()
}

// GetXmitHashPolicyOk returns a tuple with the XmitHashPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InterfaceCreate) GetXmitHashPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.XmitHashPolicy.Get(), o.XmitHashPolicy.IsSet()
}

// HasXmitHashPolicy returns a boolean if a field has been set.
func (o *InterfaceCreate) HasXmitHashPolicy() bool {
	if o != nil && o.XmitHashPolicy.IsSet() {
		return true
	}

	return false
}

// SetXmitHashPolicy gets a reference to the given NullableString and assigns it to the XmitHashPolicy field.
func (o *InterfaceCreate) SetXmitHashPolicy(v string) {
	o.XmitHashPolicy.Set(&v)
}

// SetXmitHashPolicyNil sets the value for XmitHashPolicy to be an explicit nil
func (o *InterfaceCreate) SetXmitHashPolicyNil() {
	o.XmitHashPolicy.Set(nil)
}

// UnsetXmitHashPolicy ensures that no value is present for XmitHashPolicy, not even an explicit nil
func (o *InterfaceCreate) UnsetXmitHashPolicy() {
	o.XmitHashPolicy.Unset()
}

// GetLacpduRate returns the LacpduRate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InterfaceCreate) GetLacpduRate() string {
	if o == nil || IsNil(o.LacpduRate.Get()) {
		var ret string
		return ret
	}
	return *o.LacpduRate.Get()
}

// GetLacpduRateOk returns a tuple with the LacpduRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InterfaceCreate) GetLacpduRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LacpduRate.Get(), o.LacpduRate.IsSet()
}

// HasLacpduRate returns a boolean if a field has been set.
func (o *InterfaceCreate) HasLacpduRate() bool {
	if o != nil && o.LacpduRate.IsSet() {
		return true
	}

	return false
}

// SetLacpduRate gets a reference to the given NullableString and assigns it to the LacpduRate field.
func (o *InterfaceCreate) SetLacpduRate(v string) {
	o.LacpduRate.Set(&v)
}

// SetLacpduRateNil sets the value for LacpduRate to be an explicit nil
func (o *InterfaceCreate) SetLacpduRateNil() {
	o.LacpduRate.Set(nil)
}

// UnsetLacpduRate ensures that no value is present for LacpduRate, not even an explicit nil
func (o *InterfaceCreate) UnsetLacpduRate() {
	o.LacpduRate.Unset()
}

// GetLagPorts returns the LagPorts field value if set, zero value otherwise.
func (o *InterfaceCreate) GetLagPorts() []string {
	if o == nil || IsNil(o.LagPorts) {
		var ret []string
		return ret
	}
	return o.LagPorts
}

// GetLagPortsOk returns a tuple with the LagPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetLagPortsOk() ([]string, bool) {
	if o == nil || IsNil(o.LagPorts) {
		return nil, false
	}
	return o.LagPorts, true
}

// HasLagPorts returns a boolean if a field has been set.
func (o *InterfaceCreate) HasLagPorts() bool {
	if o != nil && !IsNil(o.LagPorts) {
		return true
	}

	return false
}

// SetLagPorts gets a reference to the given []string and assigns it to the LagPorts field.
func (o *InterfaceCreate) SetLagPorts(v []string) {
	o.LagPorts = v
}

// GetVlanParentInterface returns the VlanParentInterface field value if set, zero value otherwise.
func (o *InterfaceCreate) GetVlanParentInterface() string {
	if o == nil || IsNil(o.VlanParentInterface) {
		var ret string
		return ret
	}
	return *o.VlanParentInterface
}

// GetVlanParentInterfaceOk returns a tuple with the VlanParentInterface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetVlanParentInterfaceOk() (*string, bool) {
	if o == nil || IsNil(o.VlanParentInterface) {
		return nil, false
	}
	return o.VlanParentInterface, true
}

// HasVlanParentInterface returns a boolean if a field has been set.
func (o *InterfaceCreate) HasVlanParentInterface() bool {
	if o != nil && !IsNil(o.VlanParentInterface) {
		return true
	}

	return false
}

// SetVlanParentInterface gets a reference to the given string and assigns it to the VlanParentInterface field.
func (o *InterfaceCreate) SetVlanParentInterface(v string) {
	o.VlanParentInterface = &v
}

// GetVlanTag returns the VlanTag field value if set, zero value otherwise.
func (o *InterfaceCreate) GetVlanTag() int32 {
	if o == nil || IsNil(o.VlanTag) {
		var ret int32
		return ret
	}
	return *o.VlanTag
}

// GetVlanTagOk returns a tuple with the VlanTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceCreate) GetVlanTagOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanTag) {
		return nil, false
	}
	return o.VlanTag, true
}

// HasVlanTag returns a boolean if a field has been set.
func (o *InterfaceCreate) HasVlanTag() bool {
	if o != nil && !IsNil(o.VlanTag) {
		return true
	}

	return false
}

// SetVlanTag gets a reference to the given int32 and assigns it to the VlanTag field.
func (o *InterfaceCreate) SetVlanTag(v int32) {
	o.VlanTag = &v
}

// GetVlanPcp returns the VlanPcp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InterfaceCreate) GetVlanPcp() int32 {
	if o == nil || IsNil(o.VlanPcp.Get()) {
		var ret int32
		return ret
	}
	return *o.VlanPcp.Get()
}

// GetVlanPcpOk returns a tuple with the VlanPcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InterfaceCreate) GetVlanPcpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VlanPcp.Get(), o.VlanPcp.IsSet()
}

// HasVlanPcp returns a boolean if a field has been set.
func (o *InterfaceCreate) HasVlanPcp() bool {
	if o != nil && o.VlanPcp.IsSet() {
		return true
	}

	return false
}

// SetVlanPcp gets a reference to the given NullableInt32 and assigns it to the VlanPcp field.
func (o *InterfaceCreate) SetVlanPcp(v int32) {
	o.VlanPcp.Set(&v)
}

// SetVlanPcpNil sets the value for VlanPcp to be an explicit nil
func (o *InterfaceCreate) SetVlanPcpNil() {
	o.VlanPcp.Set(nil)
}

// UnsetVlanPcp ensures that no value is present for VlanPcp, not even an explicit nil
func (o *InterfaceCreate) UnsetVlanPcp() {
	o.VlanPcp.Unset()
}

// GetMtu returns the Mtu field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InterfaceCreate) GetMtu() int32 {
	if o == nil || IsNil(o.Mtu.Get()) {
		var ret int32
		return ret
	}
	return *o.Mtu.Get()
}

// GetMtuOk returns a tuple with the Mtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InterfaceCreate) GetMtuOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mtu.Get(), o.Mtu.IsSet()
}

// HasMtu returns a boolean if a field has been set.
func (o *InterfaceCreate) HasMtu() bool {
	if o != nil && o.Mtu.IsSet() {
		return true
	}

	return false
}

// SetMtu gets a reference to the given NullableInt32 and assigns it to the Mtu field.
func (o *InterfaceCreate) SetMtu(v int32) {
	o.Mtu.Set(&v)
}

// SetMtuNil sets the value for Mtu to be an explicit nil
func (o *InterfaceCreate) SetMtuNil() {
	o.Mtu.Set(nil)
}

// UnsetMtu ensures that no value is present for Mtu, not even an explicit nil
func (o *InterfaceCreate) UnsetMtu() {
	o.Mtu.Unset()
}

func (o InterfaceCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfaceCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Ipv4Dhcp) {
		toSerialize["ipv4_dhcp"] = o.Ipv4Dhcp
	}
	if !IsNil(o.Ipv6Auto) {
		toSerialize["ipv6_auto"] = o.Ipv6Auto
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.FailoverCritical) {
		toSerialize["failover_critical"] = o.FailoverCritical
	}
	if o.FailoverGroup.IsSet() {
		toSerialize["failover_group"] = o.FailoverGroup.Get()
	}
	if o.FailoverVhid.IsSet() {
		toSerialize["failover_vhid"] = o.FailoverVhid.Get()
	}
	if !IsNil(o.FailoverAliases) {
		toSerialize["failover_aliases"] = o.FailoverAliases
	}
	if !IsNil(o.FailoverVirtualAliases) {
		toSerialize["failover_virtual_aliases"] = o.FailoverVirtualAliases
	}
	if !IsNil(o.BridgeMembers) {
		toSerialize["bridge_members"] = o.BridgeMembers
	}
	if !IsNil(o.Stp) {
		toSerialize["stp"] = o.Stp
	}
	if !IsNil(o.LagProtocol) {
		toSerialize["lag_protocol"] = o.LagProtocol
	}
	if o.XmitHashPolicy.IsSet() {
		toSerialize["xmit_hash_policy"] = o.XmitHashPolicy.Get()
	}
	if o.LacpduRate.IsSet() {
		toSerialize["lacpdu_rate"] = o.LacpduRate.Get()
	}
	if !IsNil(o.LagPorts) {
		toSerialize["lag_ports"] = o.LagPorts
	}
	if !IsNil(o.VlanParentInterface) {
		toSerialize["vlan_parent_interface"] = o.VlanParentInterface
	}
	if !IsNil(o.VlanTag) {
		toSerialize["vlan_tag"] = o.VlanTag
	}
	if o.VlanPcp.IsSet() {
		toSerialize["vlan_pcp"] = o.VlanPcp.Get()
	}
	if o.Mtu.IsSet() {
		toSerialize["mtu"] = o.Mtu.Get()
	}
	return toSerialize, nil
}

type NullableInterfaceCreate struct {
	value *InterfaceCreate
	isSet bool
}

func (v NullableInterfaceCreate) Get() *InterfaceCreate {
	return v.value
}

func (v *NullableInterfaceCreate) Set(val *InterfaceCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfaceCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfaceCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfaceCreate(val *InterfaceCreate) *NullableInterfaceCreate {
	return &NullableInterfaceCreate{value: val, isSet: true}
}

func (v NullableInterfaceCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfaceCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
